# Site settings
title: "Table Scraps"
email: mike@ornell.as
description: "A tech-focused blog by the great/amazing/lovable Mike Ornellas"
baseurl: ""
url: "http://ornell.as"

# Build settings
markdown: kramdown
permalink: pretty
