# Site settings
title: "Breaking It Down"
email: mike@ornell.as
description: "Solving problems with the Mike Ornellas"
baseurl: ""
url: "http://ornell.as"

# Build settings
markdown: kramdown
permalink: pretty
